---
TokenConfig:
  CLIENT_ID: "<CLIENT-ID>"
  CLIENT_SECRET: "<CLIENT_SECRET>"
  GRANT_TYPE: "client_credentials"
HeaderConfig:
  X_ORGANIZATION_ID: "<X_ORGANIZATION_ID>"
  X_OWNER_ID: "<X_OWNER_ID-ID>"